### ISSUE TITLE
Retail - No Meshes?

### ISSUE THREAD

**Issue by Arymond** [kwsch/UntieUnite#1]
got the NX wip to work on the retail NSP. but assetstudio cant see any mesh everything else seems to have decrypted im nut sure if this is assetstudio's problem or not?

**Comment by ElChicoEevee** [comment]
https://www.vg-resource.com/thread-39393.html there's your answer

**Comment by kwsch** [comment]
https://github.com/Perfare/AssetStudio/issues/769

UntieUnite is dumping correctly; if whatever tool you are using to view the dumped files does not support it, then modifications to those tools / a converter is needed. Outside the scope of this project.
