### ISSUE TITLE
Switch Branch Texture2Ds Actively Changing

### ISSUE THREAD

**Issue by AsteroidPizza39** [kwsch/UntieUnite#3]
I understand that after running the tool, there is still some levels of encryption, but when previewing previewable Texture2Ds in AssetStudio, many of them were actively changing whenever I switched to it from a different asset in the list. For example, in `comm_73854ddf_dlc_0_r248013_0.bundle`, t_Pokemon_Lucario (sprite) showed the following image the first time I viewed it:
![image](https://user-images.githubusercontent.com/45804670/127227736-4b1291e0-4a01-4353-8cb7-07c1046d96e9.png)
Upon switching to Gardevoir, then back to Lucario, it appeared as follows: 
![image](https://user-images.githubusercontent.com/45804670/127227923-d6dcd2b4-e447-4d8e-ae08-7d767ae1183f.png)
Next, it appeared as: 
![image](https://user-images.githubusercontent.com/45804670/127227953-523c9e58-0340-4a72-ae62-38a1422c8d19.png)
Does anyone know if there's a file with all the cards in one, to at least have less separation if possible?

**Comment by ElChicoEevee** [comment]
you need to edit AssetStudio https://github.com/Perfare/AssetStudio/issues/769
